/**
 * Seed QS World University Rankings 2024 (100 universities)
 * Run: npm run seed:universities  or  npx tsx prisma/seed-universities.ts
 */

import 'dotenv/config';
import { Pool } from 'pg';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const connectionUrl = process.env.DIRECT_URL ?? process.env.DATABASE_URL ?? '';
if (!connectionUrl) {
  console.error('❌ DATABASE_URL or DIRECT_URL required');
  process.exit(1);
}
const pool = new Pool({ connectionString: connectionUrl });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const universities = [
  { qsRank: 1, name: "Massachusetts Institute of Technology (MIT)", country: "United States", countryCode: "US", city: "Cambridge, MA", region: "North America", type: "Private", foundedYear: 1861, totalStudents: 11574, website: "https://web.mit.edu", qsOverallScore: 100, academicReputation: 100, employerReputation: 100, facultyStudentRatio: 99.7, citationsPerFaculty: 99.9, internationalFaculty: 92.4, internationalStudents: 90.8, strongSubjects: ["Engineering", "Computer Science", "Physics", "Mathematics", "Architecture"], description: "MIT là viện công nghệ hàng đầu thế giới, nổi tiếng với nghiên cứu đột phá và văn hóa đổi mới sáng tạo." },
  { qsRank: 2, name: "Imperial College London", country: "United Kingdom", countryCode: "GB", city: "London", region: "Europe", type: "Public", foundedYear: 1907, totalStudents: 19000, website: "https://www.imperial.ac.uk", qsOverallScore: 98.5, academicReputation: 99.2, employerReputation: 98.1, facultyStudentRatio: 90.1, citationsPerFaculty: 99.4, internationalFaculty: 99.7, internationalStudents: 99.4, strongSubjects: ["Engineering", "Medicine", "Natural Sciences", "Business"], description: "Imperial College London là một trong những đại học khoa học và công nghệ hàng đầu thế giới." },
  { qsRank: 3, name: "University of Oxford", country: "United Kingdom", countryCode: "GB", city: "Oxford", region: "Europe", type: "Public", foundedYear: 1096, totalStudents: 26000, website: "https://www.ox.ac.uk", qsOverallScore: 98.9, academicReputation: 100, employerReputation: 100, facultyStudentRatio: 84.2, citationsPerFaculty: 98.7, internationalFaculty: 99.3, internationalStudents: 98.6, strongSubjects: ["Humanities", "Law", "Medicine", "Philosophy", "Politics"], description: "Đại học Oxford là trường đại học nói tiếng Anh lâu đời nhất thế giới với di sản học thuật hơn 900 năm." },
  { qsRank: 4, name: "Harvard University", country: "United States", countryCode: "US", city: "Cambridge, MA", region: "North America", type: "Private", foundedYear: 1636, totalStudents: 23000, website: "https://www.harvard.edu", qsOverallScore: 98.3, academicReputation: 100, employerReputation: 100, facultyStudentRatio: 77.8, citationsPerFaculty: 99.8, internationalFaculty: 78.1, internationalStudents: 71.6, strongSubjects: ["Law", "Business", "Medicine", "Government", "Economics"], description: "Harvard là đại học lâu đời nhất nước Mỹ, đồng thời là trường có quỹ tài trợ lớn nhất thế giới." },
  { qsRank: 5, name: "University of Cambridge", country: "United Kingdom", countryCode: "GB", city: "Cambridge", region: "Europe", type: "Public", foundedYear: 1209, totalStudents: 24000, website: "https://www.cam.ac.uk", qsOverallScore: 98.2, academicReputation: 100, employerReputation: 99.8, facultyStudentRatio: 80.5, citationsPerFaculty: 97.6, internationalFaculty: 98.9, internationalStudents: 95.4, strongSubjects: ["Natural Sciences", "Mathematics", "Engineering", "Medicine", "Economics"], description: "Đại học Cambridge là cái nôi của nhiều phát minh khoa học vĩ đại, từ lý thuyết hấp dẫn đến cấu trúc DNA." },
  { qsRank: 6, name: "ETH Zurich", country: "Switzerland", countryCode: "CH", city: "Zurich", region: "Europe", type: "Public", foundedYear: 1855, totalStudents: 22200, website: "https://ethz.ch", qsOverallScore: 93.3, academicReputation: 95.8, employerReputation: 91.7, facultyStudentRatio: 91.3, citationsPerFaculty: 96.2, internationalFaculty: 99.9, internationalStudents: 98.1, strongSubjects: ["Engineering", "Computer Science", "Architecture", "Natural Sciences"], description: "ETH Zurich là trường công nghệ hàng đầu châu Âu lục địa, nơi Albert Einstein từng theo học." },
  { qsRank: 7, name: "National University of Singapore (NUS)", country: "Singapore", countryCode: "SG", city: "Singapore", region: "Asia", type: "Public", foundedYear: 1905, totalStudents: 40000, website: "https://nus.edu.sg", qsOverallScore: 92.7, academicReputation: 95.5, employerReputation: 94.6, facultyStudentRatio: 83.7, citationsPerFaculty: 90.5, internationalFaculty: 97.5, internationalStudents: 94.3, strongSubjects: ["Engineering", "Business", "Computer Science", "Medicine", "Law"], description: "NUS là đại học hàng đầu châu Á, kết hợp hoàn hảo giữa học thuật phương Đông và phương Tây." },
  { qsRank: 8, name: "UCL (University College London)", country: "United Kingdom", countryCode: "GB", city: "London", region: "Europe", type: "Public", foundedYear: 1826, totalStudents: 42000, website: "https://www.ucl.ac.uk", qsOverallScore: 91.9, academicReputation: 97.8, employerReputation: 93.1, facultyStudentRatio: 64.8, citationsPerFaculty: 91.6, internationalFaculty: 99.6, internationalStudents: 99.2, strongSubjects: ["Medicine", "Architecture", "Law", "Social Sciences", "Engineering"], description: "UCL là đại học London lâu đời nhất, nổi tiếng với cam kết nghiên cứu không phân biệt giới tính và tôn giáo." },
  { qsRank: 9, name: "Nanyang Technological University (NTU)", country: "Singapore", countryCode: "SG", city: "Singapore", region: "Asia", type: "Public", foundedYear: 1981, totalStudents: 33000, website: "https://www.ntu.edu.sg", qsOverallScore: 91.6, academicReputation: 92.3, employerReputation: 91.0, facultyStudentRatio: 85.1, citationsPerFaculty: 94.8, internationalFaculty: 98.2, internationalStudents: 92.7, strongSubjects: ["Engineering", "Business", "Computer Science", "Art & Design", "Education"], description: "NTU là đại học trẻ nhưng đã nhanh chóng vươn lên top 10 thế giới nhờ nghiên cứu công nghệ đột phá." },
  { qsRank: 10, name: "University of Pennsylvania", country: "United States", countryCode: "US", city: "Philadelphia, PA", region: "North America", type: "Private", foundedYear: 1740, totalStudents: 22000, website: "https://www.upenn.edu", qsOverallScore: 90.8, academicReputation: 96.3, employerReputation: 97.5, facultyStudentRatio: 72.9, citationsPerFaculty: 89.9, internationalFaculty: 80.4, internationalStudents: 76.3, strongSubjects: ["Business (Wharton)", "Law", "Medicine", "Social Policy", "Engineering"], description: "UPenn là trường Ivy League do Benjamin Franklin sáng lập, nổi tiếng với Wharton School — trường kinh doanh số 1 thế giới." },
  { qsRank: 11, name: "California Institute of Technology (Caltech)", country: "United States", countryCode: "US", city: "Pasadena, CA", region: "North America", type: "Private", foundedYear: 1891, totalStudents: 2400, website: "https://www.caltech.edu", qsOverallScore: 89.1, academicReputation: 94.2, employerReputation: 88.7, facultyStudentRatio: 99.9, citationsPerFaculty: 99.2, internationalFaculty: 75.3, internationalStudents: 72.1, strongSubjects: ["Physics", "Engineering", "Astronomy", "Chemistry", "Computer Science"], description: "Caltech là viện công nghệ nhỏ nhưng cực kỳ tinh nhuệ với tỷ lệ Nobel laureate trên đầu người cao nhất thế giới." },
  { qsRank: 12, name: "University of Chicago", country: "United States", countryCode: "US", city: "Chicago, IL", region: "North America", type: "Private", foundedYear: 1890, totalStudents: 17000, website: "https://www.uchicago.edu", qsOverallScore: 88.4, academicReputation: 95.1, employerReputation: 95.2, facultyStudentRatio: 88.7, citationsPerFaculty: 85.6, internationalFaculty: 73.2, internationalStudents: 68.9, strongSubjects: ["Economics", "Law", "Social Sciences", "Business", "Philosophy"], description: "UChicago nổi tiếng với trường kinh tế học Chicago và văn hóa học thuật đặt câu hỏi về mọi thứ." },
  { qsRank: 13, name: "Princeton University", country: "United States", countryCode: "US", city: "Princeton, NJ", region: "North America", type: "Private", foundedYear: 1746, totalStudents: 8500, website: "https://www.princeton.edu", qsOverallScore: 88.2, academicReputation: 97.5, employerReputation: 96.8, facultyStudentRatio: 99.4, citationsPerFaculty: 87.1, internationalFaculty: 70.5, internationalStudents: 63.4, strongSubjects: ["Mathematics", "Physics", "Public Policy", "Computer Science", "Humanities"], description: "Princeton là Ivy League nhỏ nhất, nổi tiếng với sự tập trung vào nghiên cứu undergraduate và cơ sở vật chất tuyệt vời." },
  { qsRank: 14, name: "Cornell University", country: "United States", countryCode: "US", city: "Ithaca, NY", region: "North America", type: "Private", foundedYear: 1865, totalStudents: 25000, website: "https://www.cornell.edu", qsOverallScore: 87.6, academicReputation: 94.7, employerReputation: 93.4, facultyStudentRatio: 79.2, citationsPerFaculty: 83.4, internationalFaculty: 71.8, internationalStudents: 69.2, strongSubjects: ["Engineering", "Architecture", "Hotel Administration", "Agriculture", "Law"], description: "Cornell là Ivy League duy nhất có trường công lập, nổi tiếng với sự đa dạng ngành học độc đáo." },
  { qsRank: 15, name: "Columbia University", country: "United States", countryCode: "US", city: "New York, NY", region: "North America", type: "Private", foundedYear: 1754, totalStudents: 32000, website: "https://www.columbia.edu", qsOverallScore: 87.1, academicReputation: 95.6, employerReputation: 95.9, facultyStudentRatio: 70.1, citationsPerFaculty: 80.8, internationalFaculty: 77.3, internationalStudents: 75.8, strongSubjects: ["Journalism", "Law", "Business", "Engineering", "Social Sciences"], description: "Columbia ở tim thành phố New York, nổi tiếng với Giải Pulitzer và chương trình Core Curriculum độc đáo." },
  { qsRank: 16, name: "Johns Hopkins University", country: "United States", countryCode: "US", city: "Baltimore, MD", region: "North America", type: "Private", foundedYear: 1876, totalStudents: 26000, website: "https://www.jhu.edu", qsOverallScore: 86.4, academicReputation: 91.8, employerReputation: 88.2, facultyStudentRatio: 85.3, citationsPerFaculty: 94.7, internationalFaculty: 74.6, internationalStudents: 71.3, strongSubjects: ["Medicine", "Public Health", "International Studies", "Engineering", "Nursing"], description: "JHU là đại học nghiên cứu đầu tiên của Mỹ, dẫn đầu toàn cầu về y tế công cộng và nghiên cứu y khoa." },
  { qsRank: 17, name: "Yale University", country: "United States", countryCode: "US", city: "New Haven, CT", region: "North America", type: "Private", foundedYear: 1701, totalStudents: 14000, website: "https://www.yale.edu", qsOverallScore: 85.8, academicReputation: 96.1, employerReputation: 96.7, facultyStudentRatio: 91.2, citationsPerFaculty: 76.9, internationalFaculty: 72.4, internationalStudents: 65.1, strongSubjects: ["Law", "Drama", "Art", "Medicine", "Political Science"], description: "Yale nổi tiếng với trường luật hàng đầu và di sản nghệ thuật phong phú qua các thế kỷ." },
  { qsRank: 18, name: "University of Tokyo", country: "Japan", countryCode: "JP", city: "Tokyo", region: "Asia", type: "Public", foundedYear: 1877, totalStudents: 28000, website: "https://www.u-tokyo.ac.jp", qsOverallScore: 85.1, academicReputation: 91.5, employerReputation: 90.8, facultyStudentRatio: 76.4, citationsPerFaculty: 79.2, internationalFaculty: 37.5, internationalStudents: 22.8, strongSubjects: ["Engineering", "Natural Sciences", "Medicine", "Law", "Economics"], description: "UTokyo là trường đại học danh tiếng nhất Nhật Bản, nơi đào tạo nhiều thủ tướng và lãnh đạo doanh nghiệp hàng đầu." },
  { qsRank: 19, name: "Stanford University", country: "United States", countryCode: "US", city: "Stanford, CA", region: "North America", type: "Private", foundedYear: 1885, totalStudents: 17000, website: "https://www.stanford.edu", qsOverallScore: 98.1, academicReputation: 99.8, employerReputation: 100, facultyStudentRatio: 86.5, citationsPerFaculty: 99.5, internationalFaculty: 77.9, internationalStudents: 72.6, strongSubjects: ["Computer Science", "Business", "Engineering", "Medicine", "Law"], description: "Stanford ở trái tim Silicon Valley, đào tạo nhiều doanh nhân công nghệ nhất thế giới như Google, HP, Yahoo." },
  { qsRank: 20, name: "University of Edinburgh", country: "United Kingdom", countryCode: "GB", city: "Edinburgh", region: "Europe", type: "Public", foundedYear: 1583, totalStudents: 44000, website: "https://www.ed.ac.uk", qsOverallScore: 84.5, academicReputation: 91.2, employerReputation: 87.4, facultyStudentRatio: 62.8, citationsPerFaculty: 87.9, internationalFaculty: 98.7, internationalStudents: 97.8, strongSubjects: ["Medicine", "Informatics", "Social Sciences", "Humanities", "Law"], description: "Đại học Edinburgh là một trong những đại học cổ nhất thế giới, nằm ở thủ đô Scotland xinh đẹp." },
  { qsRank: 21, name: "Peking University", country: "China", countryCode: "CN", city: "Beijing", region: "Asia", type: "Public", foundedYear: 1898, totalStudents: 45000, website: "https://www.pku.edu.cn", qsOverallScore: 83.8, academicReputation: 91.7, employerReputation: 89.3, facultyStudentRatio: 73.1, citationsPerFaculty: 75.4, internationalFaculty: 24.3, internationalStudents: 18.7, strongSubjects: ["Chinese Language", "Law", "Economics", "Philosophy", "Natural Sciences"], description: "Đại học Bắc Kinh là linh hồn của nền học thuật Trung Quốc hiện đại, biểu tượng của phong trào trí thức tiến bộ." },
  { qsRank: 22, name: "Tsinghua University", country: "China", countryCode: "CN", city: "Beijing", region: "Asia", type: "Public", foundedYear: 1911, totalStudents: 58000, website: "https://www.tsinghua.edu.cn", qsOverallScore: 83.2, academicReputation: 90.4, employerReputation: 91.5, facultyStudentRatio: 70.8, citationsPerFaculty: 78.9, internationalFaculty: 26.1, internationalStudents: 19.4, strongSubjects: ["Engineering", "Computer Science", "Architecture", "Economics", "Management"], description: "Tsinghua là MIT của Trung Quốc — nơi đào tạo nhiều kỹ sư và lãnh đạo công nghệ xuất sắc nhất." },
  { qsRank: 23, name: "University of Melbourne", country: "Australia", countryCode: "AU", city: "Melbourne", region: "Oceania", type: "Public", foundedYear: 1853, totalStudents: 52000, website: "https://www.unimelb.edu.au", qsOverallScore: 81.7, academicReputation: 88.4, employerReputation: 87.9, facultyStudentRatio: 69.2, citationsPerFaculty: 78.4, internationalFaculty: 88.9, internationalStudents: 90.1, strongSubjects: ["Law", "Medicine", "Business", "Arts", "Engineering"], description: "Đại học Melbourne là ngôi trường hàng đầu của Úc, thường được gọi là 'Oxford của Nam Bán Cầu'." },
  { qsRank: 24, name: "Seoul National University", country: "South Korea", countryCode: "KR", city: "Seoul", region: "Asia", type: "Public", foundedYear: 1946, totalStudents: 28000, website: "https://www.snu.ac.kr", qsOverallScore: 81.0, academicReputation: 88.6, employerReputation: 91.2, facultyStudentRatio: 65.3, citationsPerFaculty: 68.7, internationalFaculty: 41.2, internationalStudents: 28.4, strongSubjects: ["Engineering", "Medicine", "Law", "Business", "Natural Sciences"], description: "SNU là đại học số 1 Hàn Quốc, đào tạo nhiều CEO và chính khách nổi tiếng nhất của đất nước Kim chi." },
  { qsRank: 25, name: "McGill University", country: "Canada", countryCode: "CA", city: "Montreal", region: "North America", type: "Public", foundedYear: 1821, totalStudents: 40000, website: "https://www.mcgill.ca", qsOverallScore: 80.5, academicReputation: 87.8, employerReputation: 84.2, facultyStudentRatio: 72.4, citationsPerFaculty: 79.8, internationalFaculty: 82.6, internationalStudents: 85.3, strongSubjects: ["Medicine", "Law", "Engineering", "Music", "Management"], description: "McGill là viên ngọc quý của Canada, nằm giữa thành phố Montreal song ngữ đầy sức sống." },
  { qsRank: 26, name: "King's College London", country: "United Kingdom", countryCode: "GB", city: "London", region: "Europe", type: "Public", foundedYear: 1829, totalStudents: 33000, website: "https://www.kcl.ac.uk", qsOverallScore: 80.1, academicReputation: 87.3, employerReputation: 86.7, facultyStudentRatio: 60.4, citationsPerFaculty: 80.3, internationalFaculty: 98.8, internationalStudents: 98.4, strongSubjects: ["Law", "Medicine", "Humanities", "Social Sciences", "Nursing"], description: "King's College London ở bờ sông Thames, là trường y nổi tiếng với hệ thống bệnh viện tích hợp độc đáo." },
  { qsRank: 27, name: "University of New South Wales (UNSW)", country: "Australia", countryCode: "AU", city: "Sydney", region: "Oceania", type: "Public", foundedYear: 1949, totalStudents: 60000, website: "https://www.unsw.edu.au", qsOverallScore: 79.8, academicReputation: 84.9, employerReputation: 83.6, facultyStudentRatio: 66.1, citationsPerFaculty: 79.6, internationalFaculty: 86.7, internationalStudents: 91.3, strongSubjects: ["Engineering", "Business", "Law", "Medicine", "Art & Design"], description: "UNSW Sydney nằm sát bãi biển Coogee, là trường đại học phát triển nhanh nhất Top 50 toàn cầu." },
  { qsRank: 28, name: "London School of Economics (LSE)", country: "United Kingdom", countryCode: "GB", city: "London", region: "Europe", type: "Public", foundedYear: 1895, totalStudents: 12000, website: "https://www.lse.ac.uk", qsOverallScore: 79.5, academicReputation: 92.7, employerReputation: 94.8, facultyStudentRatio: 50.2, citationsPerFaculty: 64.1, internationalFaculty: 99.8, internationalStudents: 99.5, strongSubjects: ["Economics", "Political Science", "Law", "Sociology", "Accounting"], description: "LSE là thành trì của kinh tế học và khoa học chính trị, đào tạo nhiều nguyên thủ quốc gia và thống đốc ngân hàng nhất." },
  { qsRank: 29, name: "University of Sydney", country: "Australia", countryCode: "AU", city: "Sydney", region: "Oceania", type: "Public", foundedYear: 1850, totalStudents: 74000, website: "https://www.sydney.edu.au", qsOverallScore: 79.2, academicReputation: 87.1, employerReputation: 85.3, facultyStudentRatio: 57.8, citationsPerFaculty: 75.4, internationalFaculty: 89.3, internationalStudents: 92.7, strongSubjects: ["Law", "Medicine", "Architecture", "Business", "Arts"], description: "Đại học Sydney là trường đại học đầu tiên của Úc, với kiến trúc Gothic tráng lệ và khuôn viên đẹp như phim." },
  { qsRank: 30, name: "University of Toronto", country: "Canada", countryCode: "CA", city: "Toronto", region: "North America", type: "Public", foundedYear: 1827, totalStudents: 93000, website: "https://www.utoronto.ca", qsOverallScore: 78.9, academicReputation: 87.4, employerReputation: 84.7, facultyStudentRatio: 63.2, citationsPerFaculty: 81.2, internationalFaculty: 78.4, internationalStudents: 82.6, strongSubjects: ["Medicine", "Engineering", "Computer Science", "Business", "Law"], description: "UofT là đại học lớn nhất Canada và là nơi AI hiện đại ra đời — Geoffrey Hinton, 'cha đẻ deep learning', từng dạy ở đây." },
  { qsRank: 31, name: "Fudan University", country: "China", countryCode: "CN", city: "Shanghai", region: "Asia", type: "Public", foundedYear: 1905, totalStudents: 45000, website: "https://www.fudan.edu.cn", qsOverallScore: 78.3, academicReputation: 85.1, employerReputation: 86.4, facultyStudentRatio: 68.9, citationsPerFaculty: 71.8, internationalFaculty: 25.7, internationalStudents: 16.3, strongSubjects: ["Medicine", "Liberal Arts", "Economics", "International Relations", "Sciences"], description: "Fudan là đại học danh giá nhất Thượng Hải, nổi tiếng với khoa học xã hội và y khoa xuất sắc." },
  { qsRank: 32, name: "Delft University of Technology", country: "Netherlands", countryCode: "NL", city: "Delft", region: "Europe", type: "Public", foundedYear: 1842, totalStudents: 26000, website: "https://www.tudelft.nl", qsOverallScore: 77.8, academicReputation: 84.3, employerReputation: 83.7, facultyStudentRatio: 73.4, citationsPerFaculty: 80.6, internationalFaculty: 96.8, internationalStudents: 94.2, strongSubjects: ["Engineering", "Architecture", "Computer Science", "Aerospace", "Industrial Design"], description: "TU Delft là trường kỹ thuật hàng đầu Châu Âu lục địa, nổi tiếng với nghiên cứu về nước, kỹ thuật dân dụng và thiết kế." },
  { qsRank: 33, name: "University of Manchester", country: "United Kingdom", countryCode: "GB", city: "Manchester", region: "Europe", type: "Public", foundedYear: 1824, totalStudents: 40000, website: "https://www.manchester.ac.uk", qsOverallScore: 77.4, academicReputation: 85.2, employerReputation: 83.5, facultyStudentRatio: 58.9, citationsPerFaculty: 78.3, internationalFaculty: 97.4, internationalStudents: 96.8, strongSubjects: ["Engineering", "Business", "Medicine", "Social Sciences", "Physics"], description: "Manchester là nơi graphene được phát minh và là trường đại học đầu tiên phân tách nguyên tử. Thành phố của Oasis và Manchester United." },
  { qsRank: 34, name: "Ludwig Maximilian University of Munich", country: "Germany", countryCode: "DE", city: "Munich", region: "Europe", type: "Public", foundedYear: 1472, totalStudents: 50000, website: "https://www.lmu.de", qsOverallScore: 76.9, academicReputation: 86.4, employerReputation: 84.1, facultyStudentRatio: 62.7, citationsPerFaculty: 72.8, internationalFaculty: 87.3, internationalStudents: 82.1, strongSubjects: ["Medicine", "Natural Sciences", "Humanities", "Law", "Business"], description: "LMU Munich là một trong những đại học lâu đời và uy tín nhất nước Đức, nơi có 38 Nobel laureate." },
  { qsRank: 35, name: "University of Hong Kong", country: "Hong Kong", countryCode: "HK", city: "Hong Kong", region: "Asia", type: "Public", foundedYear: 1911, totalStudents: 29000, website: "https://www.hku.hk", qsOverallScore: 76.5, academicReputation: 83.4, employerReputation: 82.9, facultyStudentRatio: 74.6, citationsPerFaculty: 72.1, internationalFaculty: 99.1, internationalStudents: 93.7, strongSubjects: ["Medicine", "Law", "Business", "Architecture", "Social Sciences"], description: "HKU là cửa ngõ giữa Đông và Tây, nơi học sinh từ khắp thế giới gặp nhau dưới nền trời Hong Kong sầm uất." },
  { qsRank: 36, name: "KAIST (Korea Advanced Institute of Science & Technology)", country: "South Korea", countryCode: "KR", city: "Daejeon", region: "Asia", type: "Public", foundedYear: 1971, totalStudents: 11000, website: "https://www.kaist.ac.kr", qsOverallScore: 75.9, academicReputation: 82.7, employerReputation: 83.4, facultyStudentRatio: 89.2, citationsPerFaculty: 76.4, internationalFaculty: 35.6, internationalStudents: 26.3, strongSubjects: ["Engineering", "Computer Science", "Physics", "AI", "Business"], description: "KAIST là Caltech của châu Á — nhỏ nhưng siêu tinh nhuệ, nơi Samsung và LG tuyển dụng nhân tài hàng đầu." },
  { qsRank: 37, name: "Monash University", country: "Australia", countryCode: "AU", city: "Melbourne", region: "Oceania", type: "Public", foundedYear: 1958, totalStudents: 86000, website: "https://www.monash.edu", qsOverallScore: 75.3, academicReputation: 81.8, employerReputation: 80.2, facultyStudentRatio: 62.4, citationsPerFaculty: 74.7, internationalFaculty: 87.1, internationalStudents: 93.4, strongSubjects: ["Pharmacy", "Engineering", "Business", "Law", "Medicine"], description: "Monash là đại học lớn nhất Úc với các campus trải dài từ Melbourne đến Malaysia và Nam Phi." },
  { qsRank: 38, name: "Carnegie Mellon University", country: "United States", countryCode: "US", city: "Pittsburgh, PA", region: "North America", type: "Private", foundedYear: 1900, totalStudents: 15000, website: "https://www.cmu.edu", qsOverallScore: 74.8, academicReputation: 88.9, employerReputation: 92.3, facultyStudentRatio: 84.7, citationsPerFaculty: 72.6, internationalFaculty: 72.8, internationalStudents: 75.4, strongSubjects: ["Computer Science", "Robotics", "Engineering", "Drama", "Business"], description: "CMU có khoa Computer Science được xem là số 1 thế giới — nơi Siri, Alexa và nhiều AI hàng đầu được nghiên cứu." },
  { qsRank: 39, name: "University of British Columbia", country: "Canada", countryCode: "CA", city: "Vancouver", region: "North America", type: "Public", foundedYear: 1908, totalStudents: 68000, website: "https://www.ubc.ca", qsOverallScore: 74.4, academicReputation: 83.2, employerReputation: 79.8, facultyStudentRatio: 64.1, citationsPerFaculty: 74.9, internationalFaculty: 81.3, internationalStudents: 85.7, strongSubjects: ["Medicine", "Forestry", "Engineering", "Arts", "Business"], description: "UBC nằm ở thành phố đẹp nhất Canada, với view núi tuyết và biển xanh ngay trong khuôn viên." },
  { qsRank: 40, name: "New York University (NYU)", country: "United States", countryCode: "US", city: "New York, NY", region: "North America", type: "Private", foundedYear: 1831, totalStudents: 62000, website: "https://www.nyu.edu", qsOverallScore: 74.0, academicReputation: 86.3, employerReputation: 89.4, facultyStudentRatio: 55.8, citationsPerFaculty: 68.7, internationalFaculty: 75.2, internationalStudents: 79.8, strongSubjects: ["Business (Stern)", "Law", "Film", "Arts", "Medicine"], description: "NYU là đại học đô thị lớn nhất thế giới, tọa lạc giữa trái tim Manhattan với campus trải khắp thành phố." },
  { qsRank: 41, name: "University of Zurich", country: "Switzerland", countryCode: "CH", city: "Zurich", region: "Europe", type: "Public", foundedYear: 1833, totalStudents: 27000, website: "https://www.uzh.ch", qsOverallScore: 73.6, academicReputation: 82.1, employerReputation: 79.4, facultyStudentRatio: 71.8, citationsPerFaculty: 75.2, internationalFaculty: 98.4, internationalStudents: 95.6, strongSubjects: ["Medicine", "Law", "Natural Sciences", "Veterinary", "Economics"], description: "UZH là đại học nghiên cứu lớn nhất Thụy Sĩ, là nơi Albert Einstein hoàn thành luận án tiến sĩ năm 1905." },
  { qsRank: 42, name: "University of Wisconsin-Madison", country: "United States", countryCode: "US", city: "Madison, WI", region: "North America", type: "Public", foundedYear: 1848, totalStudents: 47000, website: "https://www.wisc.edu", qsOverallScore: 73.2, academicReputation: 84.7, employerReputation: 82.3, facultyStudentRatio: 68.9, citationsPerFaculty: 77.8, internationalFaculty: 64.3, internationalStudents: 61.7, strongSubjects: ["Engineering", "Agriculture", "Business", "Education", "Medicine"], description: "UW-Madison nổi tiếng với 'Wisconsin Idea' — mọi nghiên cứu phải phục vụ người dân Wisconsin và thế giới." },
  { qsRank: 43, name: "KU Leuven", country: "Belgium", countryCode: "BE", city: "Leuven", region: "Europe", type: "Public", foundedYear: 1425, totalStudents: 60000, website: "https://www.kuleuven.be", qsOverallScore: 72.8, academicReputation: 80.6, employerReputation: 77.2, facultyStudentRatio: 71.3, citationsPerFaculty: 80.1, internationalFaculty: 92.4, internationalStudents: 90.8, strongSubjects: ["Engineering", "Medicine", "Law", "Theology", "Sciences"], description: "KU Leuven là đại học Công giáo lâu đời nhất thế giới còn hoạt động, và là trường nghiên cứu số 1 châu Âu theo Reuters." },
  { qsRank: 44, name: "Osaka University", country: "Japan", countryCode: "JP", city: "Osaka", region: "Asia", type: "Public", foundedYear: 1931, totalStudents: 23000, website: "https://www.osaka-u.ac.jp", qsOverallScore: 72.4, academicReputation: 80.3, employerReputation: 82.6, facultyStudentRatio: 74.5, citationsPerFaculty: 68.3, internationalFaculty: 33.8, internationalStudents: 20.4, strongSubjects: ["Engineering", "Medicine", "Sciences", "Laser Research", "Human Sciences"], description: "Osaka University nổi tiếng với nghiên cứu laser và y sinh học tiên tiến, đặc biệt là nghiên cứu về robot humanoid." },
  { qsRank: 45, name: "Kyoto University", country: "Japan", countryCode: "JP", city: "Kyoto", region: "Asia", type: "Public", foundedYear: 1897, totalStudents: 23000, website: "https://www.kyoto-u.ac.jp", qsOverallScore: 72.1, academicReputation: 82.7, employerReputation: 83.1, facultyStudentRatio: 70.8, citationsPerFaculty: 66.9, internationalFaculty: 35.2, internationalStudents: 19.8, strongSubjects: ["Natural Sciences", "Engineering", "Medicine", "Agriculture", "Humanities"], description: "Kyoto University nổi tiếng với tự do học thuật và nhiều Nobel laureate nhất Nhật Bản sau UTokyo." },
  { qsRank: 46, name: "Pohang University of Science and Technology (POSTECH)", country: "South Korea", countryCode: "KR", city: "Pohang", region: "Asia", type: "Private", foundedYear: 1986, totalStudents: 3500, website: "https://www.postech.ac.kr", qsOverallScore: 71.7, academicReputation: 74.2, employerReputation: 76.4, facultyStudentRatio: 99.1, citationsPerFaculty: 82.3, internationalFaculty: 32.7, internationalStudents: 18.4, strongSubjects: ["Engineering", "Sciences", "IT", "Materials Science", "Physics"], description: "POSTECH là đại học nhỏ nhưng có tỷ lệ citations/giảng viên cao hàng đầu thế giới, được POSCO Steel xây dựng năm 1986." },
  { qsRank: 47, name: "University of Auckland", country: "New Zealand", countryCode: "NZ", city: "Auckland", region: "Oceania", type: "Public", foundedYear: 1883, totalStudents: 46000, website: "https://www.auckland.ac.nz", qsOverallScore: 71.4, academicReputation: 78.2, employerReputation: 75.4, facultyStudentRatio: 65.7, citationsPerFaculty: 72.1, internationalFaculty: 84.3, internationalStudents: 88.7, strongSubjects: ["Engineering", "Medicine", "Law", "Arts", "Science"], description: "Đại học Auckland là trường hàng đầu New Zealand, tọa lạc trên thành phố ngàn núi lửa bên Thái Bình Dương." },
  { qsRank: 48, name: "Hebrew University of Jerusalem", country: "Israel", countryCode: "IL", city: "Jerusalem", region: "Middle East & Africa", type: "Public", foundedYear: 1918, totalStudents: 23000, website: "https://www.huji.ac.il", qsOverallScore: 70.8, academicReputation: 79.3, employerReputation: 74.6, facultyStudentRatio: 68.4, citationsPerFaculty: 76.2, internationalFaculty: 52.3, internationalStudents: 45.7, strongSubjects: ["Medicine", "Sciences", "Humanities", "Social Sciences", "Agriculture"], description: "HUJ được Einstein và Freud đồng sáng lập năm 1918, lưu giữ di cảo gốc của Einstein và là trường hàng đầu Trung Đông." },
  { qsRank: 49, name: "University of Amsterdam", country: "Netherlands", countryCode: "NL", city: "Amsterdam", region: "Europe", type: "Public", foundedYear: 1632, totalStudents: 40000, website: "https://www.uva.nl", qsOverallScore: 70.3, academicReputation: 80.1, employerReputation: 76.3, facultyStudentRatio: 60.8, citationsPerFaculty: 72.6, internationalFaculty: 96.7, internationalStudents: 94.1, strongSubjects: ["Social Sciences", "Humanities", "Law", "Economics", "Sciences"], description: "Đại học Amsterdam nằm giữa thành phố kênh đào thơ mộng bậc nhất châu Âu, nổi tiếng với triết học và khoa học xã hội." },
  { qsRank: 50, name: "Georgia Institute of Technology", country: "United States", countryCode: "US", city: "Atlanta, GA", region: "North America", type: "Public", foundedYear: 1885, totalStudents: 44000, website: "https://www.gatech.edu", qsOverallScore: 69.8, academicReputation: 82.4, employerReputation: 88.7, facultyStudentRatio: 74.2, citationsPerFaculty: 73.5, internationalFaculty: 63.8, internationalStudents: 65.4, strongSubjects: ["Engineering", "Computer Science", "Architecture", "Business", "Sciences"], description: "Georgia Tech là trường kỹ thuật top đầu nước Mỹ và là cái nôi của nhiều startup công nghệ Georgia." },
  { qsRank: 51, name: "Eindhoven University of Technology", country: "Netherlands", countryCode: "NL", city: "Eindhoven", region: "Europe", type: "Public", foundedYear: 1956, totalStudents: 14000, website: "https://www.tue.nl", qsOverallScore: 69.3, academicReputation: 74.2, employerReputation: 76.8, facultyStudentRatio: 79.6, citationsPerFaculty: 72.4, internationalFaculty: 95.8, internationalStudents: 91.3, strongSubjects: ["Engineering", "Industrial Design", "Applied Physics", "Computer Science", "Business"], description: "TU/e là trung tâm kỹ thuật của Thung lũng Silicon châu Âu." },
  { qsRank: 52, name: "Technical University of Munich", country: "Germany", countryCode: "DE", city: "Munich", region: "Europe", type: "Public", foundedYear: 1868, totalStudents: 50000, website: "https://www.tum.de", qsOverallScore: 69.0, academicReputation: 79.8, employerReputation: 83.2, facultyStudentRatio: 71.4, citationsPerFaculty: 73.6, internationalFaculty: 88.7, internationalStudents: 84.2, strongSubjects: ["Engineering", "Natural Sciences", "Medicine", "Business", "Informatics"], description: "TUM là trường kỹ thuật số 1 nước Đức." },
  { qsRank: 53, name: "University of Michigan", country: "United States", countryCode: "US", city: "Ann Arbor, MI", region: "North America", type: "Public", foundedYear: 1817, totalStudents: 47000, website: "https://umich.edu", qsOverallScore: 68.7, academicReputation: 84.1, employerReputation: 88.4, facultyStudentRatio: 65.3, citationsPerFaculty: 71.8, internationalFaculty: 67.2, internationalStudents: 64.9, strongSubjects: ["Engineering", "Business (Ross)", "Medicine", "Law", "Social Sciences"], description: "UMich là flagship university lớn nhất Midwest Mỹ." },
  { qsRank: 54, name: "Sorbonne University", country: "France", countryCode: "FR", city: "Paris", region: "Europe", type: "Public", foundedYear: 1257, totalStudents: 56000, website: "https://www.sorbonne-universite.fr", qsOverallScore: 68.3, academicReputation: 82.6, employerReputation: 79.4, facultyStudentRatio: 54.7, citationsPerFaculty: 67.3, internationalFaculty: 79.1, internationalStudents: 75.8, strongSubjects: ["Humanities", "Sciences", "Medicine", "Law", "Languages"], description: "Sorbonne là đại học lâu đời bậc nhất thế giới." },
  { qsRank: 55, name: "University of Copenhagen", country: "Denmark", countryCode: "DK", city: "Copenhagen", region: "Europe", type: "Public", foundedYear: 1479, totalStudents: 40000, website: "https://www.ku.dk", qsOverallScore: 67.9, academicReputation: 77.4, employerReputation: 72.1, facultyStudentRatio: 63.8, citationsPerFaculty: 77.9, internationalFaculty: 91.2, internationalStudents: 87.6, strongSubjects: ["Sciences", "Medicine", "Humanities", "Social Sciences", "Pharmacy"], description: "Đại học Copenhagen là trường lâu đời nhất Bắc Âu." },
  { qsRank: 56, name: "University of Warwick", country: "United Kingdom", countryCode: "GB", city: "Coventry", region: "Europe", type: "Public", foundedYear: 1965, totalStudents: 28000, website: "https://www.warwick.ac.uk", qsOverallScore: 67.5, academicReputation: 77.8, employerReputation: 79.2, facultyStudentRatio: 67.4, citationsPerFaculty: 70.8, internationalFaculty: 97.6, internationalStudents: 96.3, strongSubjects: ["Mathematics", "Economics", "Business", "Engineering", "Social Sciences"], description: "Warwick là ngôi sao đang lên của các đại học Anh." },
  { qsRank: 57, name: "Universidad de Buenos Aires", country: "Argentina", countryCode: "AR", city: "Buenos Aires", region: "Latin America", type: "Public", foundedYear: 1821, totalStudents: 320000, website: "https://www.uba.ar", qsOverallScore: 67.1, academicReputation: 83.4, employerReputation: 80.2, facultyStudentRatio: 40.2, citationsPerFaculty: 42.7, internationalFaculty: 31.4, internationalStudents: 28.9, strongSubjects: ["Medicine", "Law", "Engineering", "Social Sciences", "Natural Sciences"], description: "UBA là đại học miễn phí lớn nhất thế giới với 300,000 sinh viên." },
  { qsRank: 58, name: "Uppsala University", country: "Sweden", countryCode: "SE", city: "Uppsala", region: "Europe", type: "Public", foundedYear: 1477, totalStudents: 48000, website: "https://www.uu.se", qsOverallScore: 66.8, academicReputation: 76.3, employerReputation: 72.8, facultyStudentRatio: 62.1, citationsPerFaculty: 76.4, internationalFaculty: 87.9, internationalStudents: 83.2, strongSubjects: ["Sciences", "Medicine", "Law", "Humanities", "Social Sciences"], description: "Uppsala là đại học lâu đời nhất Bắc Âu (1477)." },
  { qsRank: 59, name: "University of Texas at Austin", country: "United States", countryCode: "US", city: "Austin, TX", region: "North America", type: "Public", foundedYear: 1883, totalStudents: 51000, website: "https://www.utexas.edu", qsOverallScore: 66.4, academicReputation: 79.8, employerReputation: 83.4, facultyStudentRatio: 59.3, citationsPerFaculty: 67.4, internationalFaculty: 60.1, internationalStudents: 57.8, strongSubjects: ["Engineering", "Business (McCombs)", "Law", "Natural Sciences", "Communications"], description: "UT Austin là flagship university của Texas." },
  { qsRank: 60, name: "Durham University", country: "United Kingdom", countryCode: "GB", city: "Durham", region: "Europe", type: "Public", foundedYear: 1832, totalStudents: 20000, website: "https://www.dur.ac.uk", qsOverallScore: 66.1, academicReputation: 73.9, employerReputation: 71.8, facultyStudentRatio: 76.4, citationsPerFaculty: 68.2, internationalFaculty: 96.3, internationalStudents: 95.1, strongSubjects: ["Humanities", "Social Sciences", "Sciences", "Business", "Law"], description: "Durham là Oxford của miền Bắc nước Anh." },
  { qsRank: 61, name: "Australian National University (ANU)", country: "Australia", countryCode: "AU", city: "Canberra", region: "Oceania", type: "Public", foundedYear: 1946, totalStudents: 22000, website: "https://www.anu.edu.au", qsOverallScore: 65.7, academicReputation: 75.4, employerReputation: 73.2, facultyStudentRatio: 74.8, citationsPerFaculty: 73.9, internationalFaculty: 86.4, internationalStudents: 87.3, strongSubjects: ["Politics", "Astronomy", "Humanities", "Sciences", "Policy"], description: "ANU là đại học duy nhất của Úc được thành lập bởi quốc hội." },
  { qsRank: 62, name: "University of Glasgow", country: "United Kingdom", countryCode: "GB", city: "Glasgow", region: "Europe", type: "Public", foundedYear: 1451, totalStudents: 40000, website: "https://www.gla.ac.uk", qsOverallScore: 65.3, academicReputation: 74.8, employerReputation: 71.3, facultyStudentRatio: 64.7, citationsPerFaculty: 70.4, internationalFaculty: 97.1, internationalStudents: 95.8, strongSubjects: ["Medicine", "Engineering", "Arts", "Law", "Social Sciences"], description: "Đại học Glasgow là trường lâu đời thứ 4 tại Anh." },
  { qsRank: 63, name: "University of Queensland", country: "Australia", countryCode: "AU", city: "Brisbane", region: "Oceania", type: "Public", foundedYear: 1909, totalStudents: 56000, website: "https://www.uq.edu.au", qsOverallScore: 64.9, academicReputation: 73.6, employerReputation: 72.4, facultyStudentRatio: 63.2, citationsPerFaculty: 72.8, internationalFaculty: 86.1, internationalStudents: 90.2, strongSubjects: ["Sciences", "Business", "Engineering", "Medicine", "Law"], description: "UQ nằm tại thành phố Brisbane nắng ấm." },
  { qsRank: 64, name: "Shanghai Jiao Tong University", country: "China", countryCode: "CN", city: "Shanghai", region: "Asia", type: "Public", foundedYear: 1896, totalStudents: 47000, website: "https://www.sjtu.edu.cn", qsOverallScore: 64.5, academicReputation: 78.2, employerReputation: 79.6, facultyStudentRatio: 67.8, citationsPerFaculty: 68.4, internationalFaculty: 24.8, internationalStudents: 16.7, strongSubjects: ["Engineering", "Medicine", "Sciences", "Business", "Architecture"], description: "SJTU là trường kỹ thuật lâu đời và uy tín nhất Thượng Hải." },
  { qsRank: 65, name: "Rice University", country: "United States", countryCode: "US", city: "Houston, TX", region: "North America", type: "Private", foundedYear: 1912, totalStudents: 9000, website: "https://www.rice.edu", qsOverallScore: 64.1, academicReputation: 75.3, employerReputation: 78.4, facultyStudentRatio: 97.8, citationsPerFaculty: 72.4, internationalFaculty: 66.3, internationalStudents: 61.8, strongSubjects: ["Engineering", "Architecture", "Music", "Social Sciences", "Sciences"], description: "Rice là 'Caltech của South'." },
  { qsRank: 66, name: "City University of Hong Kong", country: "Hong Kong", countryCode: "HK", city: "Hong Kong", region: "Asia", type: "Public", foundedYear: 1984, totalStudents: 21000, website: "https://www.cityu.edu.hk", qsOverallScore: 63.7, academicReputation: 72.1, employerReputation: 74.3, facultyStudentRatio: 76.8, citationsPerFaculty: 73.6, internationalFaculty: 98.7, internationalStudents: 96.2, strongSubjects: ["Engineering", "Business", "Law", "Creative Media", "Sciences"], description: "CityU là đại học trẻ nhất nhưng năng động nhất Hong Kong." },
  { qsRank: 67, name: "University of Bristol", country: "United Kingdom", countryCode: "GB", city: "Bristol", region: "Europe", type: "Public", foundedYear: 1909, totalStudents: 26000, website: "https://www.bristol.ac.uk", qsOverallScore: 63.4, academicReputation: 73.4, employerReputation: 72.6, facultyStudentRatio: 67.8, citationsPerFaculty: 69.1, internationalFaculty: 97.8, internationalStudents: 96.4, strongSubjects: ["Engineering", "Law", "Social Sciences", "Arts", "Sciences"], description: "Bristol là trường đại học cool nhất UK." },
  { qsRank: 68, name: "University of California, San Diego (UCSD)", country: "United States", countryCode: "US", city: "La Jolla, CA", region: "North America", type: "Public", foundedYear: 1960, totalStudents: 42000, website: "https://ucsd.edu", qsOverallScore: 63.0, academicReputation: 74.8, employerReputation: 74.2, facultyStudentRatio: 66.4, citationsPerFaculty: 78.9, internationalFaculty: 62.8, internationalStudents: 64.7, strongSubjects: ["Marine Biology", "Neuroscience", "Computer Science", "Engineering", "Medicine"], description: "UCSD ở bờ biển La Jolla xinh đẹp." },
  { qsRank: 69, name: "Pontificia Universidad Católica de Chile", country: "Chile", countryCode: "CL", city: "Santiago", region: "Latin America", type: "Private", foundedYear: 1888, totalStudents: 27000, website: "https://www.uc.cl", qsOverallScore: 62.7, academicReputation: 74.6, employerReputation: 73.8, facultyStudentRatio: 69.2, citationsPerFaculty: 62.3, internationalFaculty: 41.7, internationalStudents: 38.4, strongSubjects: ["Engineering", "Architecture", "Law", "Medicine", "Sciences"], description: "UC Chile là đại học hàng đầu Mỹ Latin." },
  { qsRank: 70, name: "University of Washington", country: "United States", countryCode: "US", city: "Seattle, WA", region: "North America", type: "Public", foundedYear: 1861, totalStudents: 54000, website: "https://www.washington.edu", qsOverallScore: 62.4, academicReputation: 78.4, employerReputation: 79.1, facultyStudentRatio: 55.7, citationsPerFaculty: 74.6, internationalFaculty: 62.3, internationalStudents: 59.8, strongSubjects: ["Computer Science", "Medicine", "Engineering", "Fisheries", "Law"], description: "UW Seattle nằm cạnh Microsoft và Amazon headquarters." },
  { qsRank: 71, name: "Wageningen University", country: "Netherlands", countryCode: "NL", city: "Wageningen", region: "Europe", type: "Public", foundedYear: 1918, totalStudents: 14000, website: "https://www.wur.nl", qsOverallScore: 62.1, academicReputation: 71.3, employerReputation: 68.4, facultyStudentRatio: 77.8, citationsPerFaculty: 80.7, internationalFaculty: 97.4, internationalStudents: 93.6, strongSubjects: ["Agriculture", "Food Sciences", "Environmental Sciences", "Biotechnology", "Nutrition"], description: "WUR là số 1 thế giới về khoa học nông nghiệp và thực phẩm." },
  { qsRank: 72, name: "University of Leeds", country: "United Kingdom", countryCode: "GB", city: "Leeds", region: "Europe", type: "Public", foundedYear: 1904, totalStudents: 40000, website: "https://www.leeds.ac.uk", qsOverallScore: 61.8, academicReputation: 71.8, employerReputation: 72.4, facultyStudentRatio: 62.4, citationsPerFaculty: 66.8, internationalFaculty: 97.2, internationalStudents: 96.1, strongSubjects: ["Law", "Business", "Engineering", "Social Sciences", "Arts"], description: "Leeds là đại học lớn nhất miền Bắc nước Anh theo số sinh viên quốc tế." },
  { qsRank: 73, name: "Stockholm University", country: "Sweden", countryCode: "SE", city: "Stockholm", region: "Europe", type: "Public", foundedYear: 1878, totalStudents: 33000, website: "https://www.su.se", qsOverallScore: 61.4, academicReputation: 70.8, employerReputation: 68.3, facultyStudentRatio: 60.7, citationsPerFaculty: 70.4, internationalFaculty: 88.4, internationalStudents: 84.7, strongSubjects: ["Law", "Social Sciences", "Humanities", "Sciences", "Business"], description: "Stockholm University nằm trong rừng thông giữa lòng thủ đô Thụy Điển." },
  { qsRank: 74, name: "University of Geneva", country: "Switzerland", countryCode: "CH", city: "Geneva", region: "Europe", type: "Public", foundedYear: 1559, totalStudents: 17000, website: "https://www.unige.ch", qsOverallScore: 61.1, academicReputation: 71.4, employerReputation: 68.7, facultyStudentRatio: 68.3, citationsPerFaculty: 71.8, internationalFaculty: 98.7, internationalStudents: 96.3, strongSubjects: ["International Relations", "Sciences", "Medicine", "Law", "Humanities"], description: "Đại học Geneva tọa lạc tại thành phố ngoại giao toàn cầu." },
  { qsRank: 75, name: "University of Southampton", country: "United Kingdom", countryCode: "GB", city: "Southampton", region: "Europe", type: "Public", foundedYear: 1862, totalStudents: 26000, website: "https://www.southampton.ac.uk", qsOverallScore: 60.8, academicReputation: 70.4, employerReputation: 69.8, facultyStudentRatio: 64.2, citationsPerFaculty: 68.3, internationalFaculty: 97.1, internationalStudents: 95.4, strongSubjects: ["Engineering", "Electronics", "Oceanography", "Law", "Medicine"], description: "Southampton nổi tiếng với nghiên cứu đại dương." },
  { qsRank: 76, name: "University of Groningen", country: "Netherlands", countryCode: "NL", city: "Groningen", region: "Europe", type: "Public", foundedYear: 1614, totalStudents: 34000, website: "https://www.rug.nl", qsOverallScore: 60.5, academicReputation: 70.1, employerReputation: 67.8, facultyStudentRatio: 64.8, citationsPerFaculty: 69.7, internationalFaculty: 95.4, internationalStudents: 92.8, strongSubjects: ["Sciences", "Medicine", "Economics", "Law", "Humanities"], description: "Đại học Groningen là nơi Heike Kamerlingh Onnes khám phá hiện tượng siêu dẫn." },
  { qsRank: 77, name: "Boston University", country: "United States", countryCode: "US", city: "Boston, MA", region: "North America", type: "Private", foundedYear: 1839, totalStudents: 36000, website: "https://www.bu.edu", qsOverallScore: 60.2, academicReputation: 74.3, employerReputation: 76.4, facultyStudentRatio: 65.2, citationsPerFaculty: 62.8, internationalFaculty: 68.4, internationalStudents: 72.3, strongSubjects: ["Communications", "Engineering", "Business", "Law", "Medicine"], description: "BU trải dài dọc bờ sông Charles ở Boston." },
  { qsRank: 78, name: "Hebrew University of Jerusalem (HUJI)", country: "Israel", countryCode: "IL", city: "Jerusalem", region: "Middle East & Africa", type: "Public", foundedYear: 1918, totalStudents: 23000, website: "https://new.huji.ac.il", qsOverallScore: 59.9, academicReputation: 70.8, employerReputation: 66.4, facultyStudentRatio: 64.7, citationsPerFaculty: 72.3, internationalFaculty: 48.7, internationalStudents: 41.2, strongSubjects: ["Sciences", "Medicine", "Humanities", "Law", "Agriculture"], description: "HUJI lưu giữ toàn bộ di cảo gốc của Albert Einstein." },
  { qsRank: 79, name: "Pontificia Universidad Javeriana", country: "Colombia", countryCode: "CO", city: "Bogotá", region: "Latin America", type: "Private", foundedYear: 1623, totalStudents: 38000, website: "https://www.javeriana.edu.co", qsOverallScore: 59.6, academicReputation: 68.4, employerReputation: 71.2, facultyStudentRatio: 66.8, citationsPerFaculty: 58.3, internationalFaculty: 38.4, internationalStudents: 29.7, strongSubjects: ["Law", "Medicine", "Engineering", "Communications", "Architecture"], description: "Javeriana là đại học Dòng Tên lâu đời nhất Colombia." },
  { qsRank: 80, name: "Lomonosov Moscow State University", country: "Russia", countryCode: "RU", city: "Moscow", region: "Europe", type: "Public", foundedYear: 1755, totalStudents: 47000, website: "https://www.msu.ru", qsOverallScore: 59.3, academicReputation: 74.8, employerReputation: 72.3, facultyStudentRatio: 58.7, citationsPerFaculty: 42.6, internationalFaculty: 15.3, internationalStudents: 18.4, strongSubjects: ["Mathematics", "Physics", "Chemistry", "Humanities", "Economics"], description: "MSU Moscow là đại học lâu đời nhất nước Nga." },
  { qsRank: 81, name: "Universidad Nacional Autónoma de México (UNAM)", country: "Mexico", countryCode: "MX", city: "Mexico City", region: "Latin America", type: "Public", foundedYear: 1551, totalStudents: 350000, website: "https://www.unam.mx", qsOverallScore: 59.0, academicReputation: 76.4, employerReputation: 73.8, facultyStudentRatio: 38.4, citationsPerFaculty: 38.7, internationalFaculty: 25.3, internationalStudents: 19.8, strongSubjects: ["Medicine", "Law", "Engineering", "Sciences", "Humanities"], description: "UNAM là đại học lớn nhất Tây Bán Cầu." },
  { qsRank: 82, name: "KTH Royal Institute of Technology", country: "Sweden", countryCode: "SE", city: "Stockholm", region: "Europe", type: "Public", foundedYear: 1827, totalStudents: 18000, website: "https://www.kth.se", qsOverallScore: 58.7, academicReputation: 73.4, employerReputation: 76.8, facultyStudentRatio: 65.4, citationsPerFaculty: 64.2, internationalFaculty: 85.7, internationalStudents: 80.4, strongSubjects: ["Engineering", "Technology", "Computer Science", "Architecture", "Biotech"], description: "KTH là MIT của Bắc Âu." },
  { qsRank: 83, name: "University of Birmingham", country: "United Kingdom", countryCode: "GB", city: "Birmingham", region: "Europe", type: "Public", foundedYear: 1900, totalStudents: 38000, website: "https://www.birmingham.ac.uk", qsOverallScore: 58.4, academicReputation: 70.2, employerReputation: 71.4, facultyStudentRatio: 64.7, citationsPerFaculty: 64.8, internationalFaculty: 97.3, internationalStudents: 96.2, strongSubjects: ["Engineering", "Medicine", "Law", "Business", "Humanities"], description: "Birmingham là trường Redbrick đầu tiên của Anh." },
  { qsRank: 84, name: "Washington University in St. Louis", country: "United States", countryCode: "US", city: "St. Louis, MO", region: "North America", type: "Private", foundedYear: 1853, totalStudents: 16000, website: "https://wustl.edu", qsOverallScore: 58.1, academicReputation: 74.8, employerReputation: 77.4, facultyStudentRatio: 84.3, citationsPerFaculty: 66.7, internationalFaculty: 65.2, internationalStudents: 62.8, strongSubjects: ["Medicine", "Law", "Business (Olin)", "Engineering", "Arts"], description: "WashU là Ivy của Midwest." },
  { qsRank: 85, name: "University of Helsinki", country: "Finland", countryCode: "FI", city: "Helsinki", region: "Europe", type: "Public", foundedYear: 1640, totalStudents: 33000, website: "https://www.helsinki.fi", qsOverallScore: 57.8, academicReputation: 68.4, employerReputation: 64.3, facultyStudentRatio: 62.8, citationsPerFaculty: 72.1, internationalFaculty: 82.4, internationalStudents: 77.8, strongSubjects: ["Sciences", "Medicine", "Humanities", "Social Sciences", "Law"], description: "Đại học Helsinki là cái nôi trí thức của Phần Lan." },
  { qsRank: 86, name: "University of Vienna", country: "Austria", countryCode: "AT", city: "Vienna", region: "Europe", type: "Public", foundedYear: 1365, totalStudents: 92000, website: "https://www.univie.ac.at", qsOverallScore: 57.5, academicReputation: 71.2, employerReputation: 67.4, facultyStudentRatio: 46.8, citationsPerFaculty: 64.7, internationalFaculty: 91.3, internationalStudents: 88.7, strongSubjects: ["Humanities", "Sciences", "Law", "Medicine", "Social Sciences"], description: "Đại học Vienna là trường đại học lâu đời nhất thế giới nói tiếng Đức." },
  { qsRank: 87, name: "Hong Kong University of Science and Technology", country: "Hong Kong", countryCode: "HK", city: "Hong Kong", region: "Asia", type: "Public", foundedYear: 1991, totalStudents: 16000, website: "https://www.ust.hk", qsOverallScore: 57.2, academicReputation: 72.8, employerReputation: 74.1, facultyStudentRatio: 78.4, citationsPerFaculty: 68.4, internationalFaculty: 98.4, internationalStudents: 93.7, strongSubjects: ["Engineering", "Business", "Sciences", "Computer Science", "Social Sciences"], description: "HKUST là đại học trẻ nhất nhưng tăng hạng nhanh nhất thế giới." },
  { qsRank: 88, name: "University of Notre Dame", country: "United States", countryCode: "US", city: "Notre Dame, IN", region: "North America", type: "Private", foundedYear: 1842, totalStudents: 13000, website: "https://www.nd.edu", qsOverallScore: 57.0, academicReputation: 72.4, employerReputation: 76.8, facultyStudentRatio: 82.4, citationsPerFaculty: 58.3, internationalFaculty: 57.8, internationalStudents: 54.2, strongSubjects: ["Law", "Business (Mendoza)", "Theology", "Engineering", "Arts"], description: "Notre Dame là trường Công giáo hàng đầu nước Mỹ." },
  { qsRank: 89, name: "University of California, Los Angeles (UCLA)", country: "United States", countryCode: "US", city: "Los Angeles, CA", region: "North America", type: "Public", foundedYear: 1919, totalStudents: 47000, website: "https://www.ucla.edu", qsOverallScore: 56.7, academicReputation: 80.4, employerReputation: 83.2, facultyStudentRatio: 57.4, citationsPerFaculty: 67.8, internationalFaculty: 62.3, internationalStudents: 60.4, strongSubjects: ["Film", "Engineering", "Medicine", "Law", "Business (Anderson)"], description: "UCLA ở giữa Los Angeles sunshine." },
  { qsRank: 90, name: "Vanderbilt University", country: "United States", countryCode: "US", city: "Nashville, TN", region: "North America", type: "Private", foundedYear: 1873, totalStudents: 13500, website: "https://www.vanderbilt.edu", qsOverallScore: 56.4, academicReputation: 72.8, employerReputation: 75.4, facultyStudentRatio: 84.7, citationsPerFaculty: 64.2, internationalFaculty: 60.4, internationalStudents: 57.8, strongSubjects: ["Medicine", "Education", "Law", "Business (Owen)", "Engineering"], description: "Vanderbilt là 'Ivy' của Deep South." },
  { qsRank: 91, name: "University of California, Berkeley", country: "United States", countryCode: "US", city: "Berkeley, CA", region: "North America", type: "Public", foundedYear: 1868, totalStudents: 45000, website: "https://www.berkeley.edu", qsOverallScore: 56.1, academicReputation: 85.4, employerReputation: 86.7, facultyStudentRatio: 58.7, citationsPerFaculty: 70.4, internationalFaculty: 63.8, internationalStudents: 61.2, strongSubjects: ["Computer Science", "Engineering", "Social Sciences", "Business (Haas)", "Law"], description: "UC Berkeley là đại học công lập hàng đầu thế giới." },
  { qsRank: 92, name: "Erasmus University Rotterdam", country: "Netherlands", countryCode: "NL", city: "Rotterdam", region: "Europe", type: "Public", foundedYear: 1913, totalStudents: 32000, website: "https://www.eur.nl", qsOverallScore: 55.8, academicReputation: 67.8, employerReputation: 72.4, facultyStudentRatio: 59.3, citationsPerFaculty: 64.7, internationalFaculty: 94.8, internationalStudents: 91.3, strongSubjects: ["Economics", "Business (RSM)", "Medicine", "Law", "Social Sciences"], description: "Erasmus Rotterdam nằm trong thành phố cảng hiện đại nhất châu Âu." },
  { qsRank: 93, name: "University of Alberta", country: "Canada", countryCode: "CA", city: "Edmonton", region: "North America", type: "Public", foundedYear: 1908, totalStudents: 40000, website: "https://www.ualberta.ca", qsOverallScore: 55.5, academicReputation: 70.4, employerReputation: 68.7, facultyStudentRatio: 67.4, citationsPerFaculty: 63.8, internationalFaculty: 74.3, internationalStudents: 78.6, strongSubjects: ["Engineering", "Medicine", "Sciences", "Business", "Education"], description: "UAlberta là trường hàng đầu Canada về nghiên cứu dầu khí và AI." },
  { qsRank: 94, name: "Yonsei University", country: "South Korea", countryCode: "KR", city: "Seoul", region: "Asia", type: "Private", foundedYear: 1885, totalStudents: 40000, website: "https://www.yonsei.ac.kr", qsOverallScore: 55.2, academicReputation: 74.2, employerReputation: 76.8, facultyStudentRatio: 63.7, citationsPerFaculty: 56.4, internationalFaculty: 37.8, internationalStudents: 30.4, strongSubjects: ["Medicine", "Business", "Engineering", "Law", "Humanities"], description: "Yonsei là một trong SKY universities." },
  { qsRank: 95, name: "University of Cologne", country: "Germany", countryCode: "DE", city: "Cologne", region: "Europe", type: "Public", foundedYear: 1388, totalStudents: 52000, website: "https://www.uni-koeln.de", qsOverallScore: 54.9, academicReputation: 67.3, employerReputation: 69.8, facultyStudentRatio: 54.8, citationsPerFaculty: 62.4, internationalFaculty: 84.7, internationalStudents: 80.3, strongSubjects: ["Law", "Economics", "Medicine", "Social Sciences", "Humanities"], description: "Đại học Cologne là một trong những đại học lâu đời nhất Đức." },
  { qsRank: 96, name: "University of Lausanne", country: "Switzerland", countryCode: "CH", city: "Lausanne", region: "Europe", type: "Public", foundedYear: 1537, totalStudents: 15000, website: "https://www.unil.ch", qsOverallScore: 54.6, academicReputation: 68.4, employerReputation: 64.7, facultyStudentRatio: 68.2, citationsPerFaculty: 68.8, internationalFaculty: 98.4, internationalStudents: 96.1, strongSubjects: ["Medicine", "Law", "Humanities", "Sciences", "Social Sciences"], description: "Đại học Lausanne nhìn ra hồ Leman và dãy Alps." },
  { qsRank: 97, name: "University of Science and Technology of China", country: "China", countryCode: "CN", city: "Hefei", region: "Asia", type: "Public", foundedYear: 1958, totalStudents: 17000, website: "https://en.ustc.edu.cn", qsOverallScore: 54.3, academicReputation: 71.8, employerReputation: 68.4, facultyStudentRatio: 81.4, citationsPerFaculty: 75.2, internationalFaculty: 22.4, internationalStudents: 14.7, strongSubjects: ["Physics", "Computer Science", "Mathematics", "Engineering", "Chemistry"], description: "USTC là 'MIT của Trung Quốc'." },
  { qsRank: 98, name: "Emory University", country: "United States", countryCode: "US", city: "Atlanta, GA", region: "North America", type: "Private", foundedYear: 1836, totalStudents: 15000, website: "https://www.emory.edu", qsOverallScore: 54.0, academicReputation: 69.4, employerReputation: 72.8, facultyStudentRatio: 77.8, citationsPerFaculty: 66.3, internationalFaculty: 62.4, internationalStudents: 59.7, strongSubjects: ["Medicine", "Law", "Business (Goizueta)", "Public Health", "Theology"], description: "Emory ở Atlanta có CDC và CNN cạnh nhà." },
  { qsRank: 99, name: "University of Nottingham", country: "United Kingdom", countryCode: "GB", city: "Nottingham", region: "Europe", type: "Public", foundedYear: 1881, totalStudents: 33000, website: "https://www.nottingham.ac.uk", qsOverallScore: 53.7, academicReputation: 70.2, employerReputation: 71.4, facultyStudentRatio: 64.8, citationsPerFaculty: 62.7, internationalFaculty: 97.4, internationalStudents: 96.2, strongSubjects: ["Engineering", "Pharmacy", "Business", "Medicine", "Law"], description: "Nottingham nổi tiếng với campus xanh đẹp nhất UK." },
  { qsRank: 100, name: "Indian Institute of Technology Bombay (IIT Bombay)", country: "India", countryCode: "IN", city: "Mumbai", region: "Asia", type: "Public", foundedYear: 1958, totalStudents: 10000, website: "https://www.iitb.ac.in", qsOverallScore: 53.4, academicReputation: 73.4, employerReputation: 79.2, facultyStudentRatio: 76.4, citationsPerFaculty: 54.8, internationalFaculty: 18.4, internationalStudents: 11.2, strongSubjects: ["Engineering", "Computer Science", "Sciences", "Design", "Management"], description: "IIT Bombay là viện kỹ thuật uy tín nhất Ấn Độ." },
];

async function main() {
  for (const u of universities) {
    await prisma.university_rankings.upsert({
      where: { qs_rank: u.qsRank },
      update: {
        name: u.name,
        country: u.country,
        country_code: u.countryCode,
        city: u.city,
        region: u.region,
        type: u.type,
        founded_year: u.foundedYear,
        total_students: u.totalStudents,
        website: u.website ?? null,
        qs_overall_score: u.qsOverallScore,
        academic_reputation: u.academicReputation,
        employer_reputation: u.employerReputation,
        faculty_student_ratio: u.facultyStudentRatio,
        citations_per_faculty: u.citationsPerFaculty,
        international_faculty: u.internationalFaculty,
        international_students: u.internationalStudents,
        strong_subjects: u.strongSubjects,
        description: u.description ?? null,
      },
      create: {
        qs_rank: u.qsRank,
        name: u.name,
        country: u.country,
        country_code: u.countryCode,
        city: u.city,
        region: u.region,
        type: u.type,
        founded_year: u.foundedYear,
        total_students: u.totalStudents,
        website: u.website ?? null,
        qs_overall_score: u.qsOverallScore,
        academic_reputation: u.academicReputation,
        employer_reputation: u.employerReputation,
        faculty_student_ratio: u.facultyStudentRatio,
        citations_per_faculty: u.citationsPerFaculty,
        international_faculty: u.internationalFaculty,
        international_students: u.internationalStudents,
        strong_subjects: u.strongSubjects,
        description: u.description ?? null,
      },
    });
  }
  console.log(`✅ Seeded ${universities.length} universities`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
    await pool.end();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    await pool.end();
    process.exit(1);
  });
